---
- name: "Setup demo"
  hosts: openshift

  vars:
    openshift_url: "{{ lookup('env', 'OPENSHIFT_URL') }}"
    openshift_user: "{{ lookup('env', 'OPENSHIFT_USER') }}"
    openshift_password: "{{ lookup('env', 'OPENSHIFT_PASSWORD') }}"

  pre_tasks:
  - include_vars:
      dir: 'vars'
      extensions:
          - json
  - include_vars:
      dir: 'templates'
      extensions:
          - json

  roles:
    - openshift-defaults
    - create-openshift-resources