---
- name: "Setup demo"
  hosts: openshift

  vars:
    openshift_url: "{{ lookup('env', 'OPENSHIFT_URL') }}"
    openshift_user: "{{ lookup('env', 'OPENSHIFT_USER') }}"
    openshift_password: "{{ lookup('env', 'OPENSHIFT_PASSWORD') }}"

  pre_tasks:
  - include_vars:
      file: 'vars/project-names.json'
  - include_vars:
      file: 'templates/master.json'

  roles:
    - openshift-defaults
    - create-openshift-resources